<template>
<div class="page-section"><div class="home-card"><div class="card-header"><span class="card-title"><span class="title-dot"></span>招生管理</span></div><div class="card-body"><el-tabs type="border-card">
<el-tab-pane label="招生目录"><el-button type="primary" size="small" round style="margin-bottom:12px" @click="openDlg('add')">新增专业</el-button><el-table :data="catalog" size="small" stripe empty-text="暂无数据"><el-table-column prop="name" label="专业名称" min-width="160"/><el-table-column prop="dir" label="研究方向" min-width="160"/><el-table-column prop="advisor" label="导师" width="100"/><el-table-column prop="quota" label="招生人数" width="80"/><el-table-column label="操作" width="200"><template #default="{row}"><el-button text type="primary" size="small" @click="viewDlg(row)">详情</el-button><el-button text type="warning" size="small" @click="editDlg(row)">编辑</el-button><el-button text type="success" size="small" @click="printDlg(row)">打印</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="报名管理"><el-input v-model="kw" placeholder="搜索考生..." style="width:260px;margin-bottom:12px" clearable/><el-table :data="regs" size="small" stripe empty-text="暂无数据"><el-table-column prop="id" label="编号" width="130"/><el-table-column prop="name" label="姓名" width="80"/><el-table-column prop="type" label="类别" width="80"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='已确认'?'success':'warning'" size="small" round>{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="200"><template #default="{row}"><el-button text type="primary" size="small" @click="viewDlg(row)">详情</el-button><el-button text type="warning" size="small" @click="editDlg(row)">审核</el-button><el-button text type="success" size="small" @click="printDlg(row)">打印</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="成绩管理"><el-table :data="scores" size="small" stripe empty-text="暂无数据"><el-table-column prop="id" label="编号" width="130"/><el-table-column prop="name" label="姓名" width="80"/><el-table-column prop="first" label="初试" width="70"/><el-table-column prop="second" label="复试" width="70"/><el-table-column prop="total" label="综合" width="70"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='已录取'?'success':'warning'" size="small" round>{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="200"><template #default="{row}"><el-button text type="primary" size="small" @click="viewDlg(row)">详情</el-button><el-button text type="warning" size="small" @click="editDlg(row)">修改</el-button><el-button text type="success" size="small" @click="printDlg(row)">打印</el-button></template></el-table-column></el-table></el-tab-pane>
</el-tabs>

<el-dialog v-model="dlg.show" :title="dlg.title" width="580px"><el-descriptions v-if="dlg.mode==='view'" :column="2" border size="small"><el-descriptions-item v-for="(v,k) in dlg.row" :key="k" :label="String(k)"><span>{{v||'-'}}</span></el-descriptions-item></el-descriptions><el-form v-else-if="dlg.mode==='edit'" :model="dlg.row" label-width="90px"><el-form-item v-for="(v,k) in dlg.row" :key="k" :label="String(k)"><el-input v-model="dlg.row[k]"/></el-form-item></el-form><div v-else style="text-align:center"><h3 style="color:#153D97;margin-bottom:16px">{{dlg.title}}</h3><table style="width:100%;border-collapse:collapse;font-size:13px"><tr v-for="(v,k) in dlg.row" :key="k" style="border-bottom:1px solid #f0f0f0"><td style="padding:8px 12px;font-weight:600;width:100px;background:#f8fafc">{{k}}</td><td style="padding:8px 12px">{{v||'-'}}</td></tr></table></div><template #footer><span v-if="dlg.mode==='view'"><el-button type="warning" @click="dlg.mode='edit'">编辑</el-button><el-button type="success" @click="dlg.mode='print'">打印</el-button><el-button @click="dlg.show=false">关闭</el-button></span><span v-else-if="dlg.mode==='edit'"><el-button @click="dlg.mode='view'">取消</el-button><el-button type="primary" @click="dlg.show=false">保存</el-button></span><span v-else><el-button type="primary" @click="window.print()">打印</el-button><el-button @click="dlg.mode='view'">返回</el-button></span></template></el-dialog></div></div></div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';const kw=ref('');const catalog=ref([{name:'计算机科学与技术',dir:'人工智能',advisor:'李教授',quota:5,exam:'政治/英语/数学/专业课'},{name:'计算机科学与技术',dir:'数据科学',advisor:'王教授',quota:3,exam:'政治/英语/数学/专业课'}]);const regs=ref([{id:'20261001001',name:'考生A',type:'统考',status:'已确认'},{id:'20261001002',name:'考生B',type:'推免',status:'已确认'}]);const scores=ref([{id:'20261001001',name:'考生A',first:385,second:88,total:473,status:'待录取'},{id:'20261001002',name:'考生B',first:402,second:92,total:494,status:'已录取'}]);const dlg=reactive({show:false,title:'',mode:'view',row:{} as any});function viewDlg(row:any){dlg.row={...row};dlg.title='详情';dlg.mode='view';dlg.show=true}function editDlg(row:any){dlg.row={...row};dlg.title='编辑';dlg.mode='edit';dlg.show=true}function printDlg(row:any){dlg.row={...row};dlg.title='打印';dlg.mode='print';dlg.show=true}function openDlg(mode:string){const r={name:'',dir:'',advisor:'',quota:0,exam:''};catalog.value.unshift(r);editDlg(r)}</script>
<style scoped>.page-section{max-width:1200px}</style>
